### ISSUE TITLE
Review documentation and comments

### ISSUE THREAD

**Issue by adammunoz** [rakuten-frontend/rakuten-react-kit#12]

**Comment by adammunoz** [comment]
@10chars 

Can you work on this?

**Comment by 10chars** [comment]
@adammunoz What needs to be done?

**Comment by adammunoz** [comment]
I was thinking that you could correct some of the English in the comments?
It's just small grammatical mistakes but it gives it better readability.

**Comment by adammunoz** [comment]
Or it might be a good task for Josh?
