### ISSUE TITLE
Accessing PropTypes via the main React is deprecated

### ISSUE THREAD

**Issue by rogeriotaques** [rakuten-frontend/rakuten-react-kit#23]
Guys,

After clone RRK repository and run `npm start`, the app shows the following warning in the console. 

```
Warning: Accessing PropTypes via the main React package is deprecated. 
Use the prop-types package from npm instead.
```

**Comment by adammunoz** [comment]
Hey @rogeriotaques 

It's just a development warning related to one of the dependencies using deprecated syntax in React 15.5.

It won't show in production, but we are going to look at it. Thanks a lot for reporting.

**Comment by rogeriotaques** [comment]
Hi @adammunoz !

I see, thanks for clarify and check that! It might not be a problem, then. But just in case, I'm leaving this treat open and you can close it whenever you think it won't be useful anymore.

**Comment by adammunoz** [comment]
Yeah please, let’s leave it open until we fix it.

--
Munoz, Adan | Makyn | COED
Marketing & UX CoE Department/Front End Technology Group
Rakuten, Inc.

**Comment by adammunoz** [comment]
Traced back to Babel.

https://github.com/babel/babel/issues/5705

**Comment by hrnkoji** [comment]
https://github.com/rakuten-frontend/rakuten-react-kit/pull/32
It solved with this PR.

**Comment by adammunoz** [comment]
Thanks @hrnkoji !
