### ISSUE TITLE
sass-lint

### ISSUE THREAD

**Issue by linmic** [rakuten-frontend/rakuten-react-kit#26]
Would you consider using [sass-lint](https://github.com/sasstools/sass-lint)? I believe it makes the code clean and keep the style consistency across projects. Same as ESLint for javascript.

**Comment by rogeriotaques** [comment]
It seems interesting @adammunoz, don't you?

**Comment by adammunoz** [comment]
@linmic Yes. Can you please send PR?

**Comment by linmic** [comment]
@adammunoz Sure, I'm on it.
