### ISSUE TITLE
prettier

### ISSUE THREAD

**Issue by linmic** [rakuten-frontend/rakuten-react-kit#27]
[Prettier](https://github.com/prettier/prettier) can be a good fit for development and can be used with ESLint (kinda need some adjustments to make them work better together, rules wise). But it does save us lots of time from manually linting the code ourselves, not to mention lots of superstar projects have used this for a while.

**Comment by rogeriotaques** [comment]
+1 @adammunoz, I'm using Prettier along RRK, EditorConfig and ESLint in VSCode and it's working very well. :) I believe we should consider in making it an "official" recommendation.

**Comment by adammunoz** [comment]
@linmic @rogeriotaques 

It seems interesting. Let's talk about it.

**Comment by linmic** [comment]
Some might argue that it's an opinionated tool without configurable ruleset. However, I think it's better for development in a big picture for several reasons, as stated in the official document.

> - “We want to free mental threads and end discussions around style. While sometimes fruitful, these discussions are for the most part wasteful.”
> - “Literally had an engineer go through a huge effort of cleaning up all of our code because we were debating ternary style for the longest time and were inconsistent about it. It was dumb, but it was a weird on-going "great debate" that wasted lots of little back and forth bits. It's far easier for us all to agree now: just run Prettier, and go with that style.”
> - “Getting tired telling people how to style their product code.”
> - “Our top reason was to stop wasting our time debating style nits.”
> - “Having a githook set up has reduced the amount of style issues in PRs that result in broken builds due to ESLint rules or things I have to nit-pick or clean up later.”
> - “I don't want anybody to nitpick any other person ever again.”
> - “It reminds me of how Steve Jobs used to wear the same clothes every day because he has a million decisions to make and he didn't want to be bothered to make trivial ones like picking out clothes. I think Prettier is like that.”

and of course, it's mostly compatible with ESLint, with them combined I can really say the advantages actually do outweigh the disadvantages.

And to be honest, we don't have to hassle telling any new members how to format their code anymore once the mechanism is set for all projects.

**Comment by adammunoz** [comment]
Solved by #36
