### ISSUE TITLE
Often render the number of HMR

### ISSUE THREAD

**Issue by hrnkoji** [rakuten-frontend/rakuten-react-kit#6]
With certain conditions after hot code is pushed rendering occurs many times.

**Comment by adammunoz** [comment]
@hrnkoji 

Can you send a test case?

Thank you

**Comment by adammunoz** [comment]
Solved in https://github.com/rakuten-frontend/rakuten-react-kit/commit/cc916920f63a9f798c8fd9d764f0bab9e344d178
